### PR TITLE
Updating example data formats to consistent NetCDF4

### LINKED ISSUE #585: Windows 3.12 tests are failing
**Describe the bug**

The tests across multiple PRs are failing on CI for Windows with Python 3.12. For example:

https://github.com/ImperialCollegeLondon/virtual_ecosystem/actions/runs/11271229156/job/31344168042?pr=583

My first guess here is that we have inconsistent NetCDF file formats in our `example_data/data` directory:

```sh
➜  data git:(develop) ✗ for f in *.nc; do
for> echo $f  
for> ncdump -k $f
for> done
example_climate_data.nc
netCDF-4
example_elevation_data.nc
netCDF-4
example_litter_data.nc
netCDF-4
example_plant_data.nc
64-bit offset
example_soil_data.nc
netCDF-4
example_surface_runoff_data.nc
netCDF-4
example_topofcanopy_radiation.nc
64-bit offset
```

I think it is choking on those NetCDF-3 64-bit offset files. Or at least that's what I'm going to try and fix first

### PR DESCRIPTION
**Pull request by davidorme**
# Description

This is a first attempt to solve the failing tests issue on Windows 3.12 by updating two example data files from NetCDF3 to NetCDF4

Fixes #585 (issue)

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [x] Bug fix (non-breaking change which fixes an issue)

## Key checklist

- [x] Make sure you've run the `pre-commit` checks: `$ pre-commit run -a`
- [x] All tests pass: `$ poetry run pytest`

## Further checks

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works
- [ ] Relevant documentation reviewed and updated

### CODE REVIEW

**Comment by davidorme** [comment]
Hmm - still fails, but on different files. I'd forgotten that the testing files included a `data` directory with `.nc` files.

**Comment by davidorme** [comment]
Aha! That seems to have done it.

**Review by jacobcook1995 — APPROVED** [review]
LGTM!

**Comment by davidorme** [comment]
Annoyingly all the files have gotten larger. They're still small, but 🤷‍♂️ 

We _could_ add compression but that adds performance overheads in reading.

**Pull request merged**
