### PR TITLE
Feature/bypass flow

### PR DESCRIPTION
**Pull request by vgro**
This PR adds preferential bypass flow, i.e. the flow that bypasses the soil matrix and drains directly to the groundwater. This represents the famous 'pipes'. The shape parameter will need some further investigation and sensitivity analysis.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Key checklist

- [x] Make sure you've run the `pre-commit` checks: `$ pre-commit run -a`
- [x] All tests pass: `$ poetry run pytest`

## Further checks

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Review by davidorme — APPROVED** [review]
LGTM - this makes a lot of sense and that LISFLOOD solution looks very pragmatic. It would be good to add citations and maybe a slightly fuller explanatation of the shape parameter. I didn't really get it until I went to look at 
https://ec-jrc.github.io/lisflood-model/2_09_stdLISFLOOD_preferential-bypass

This does need docs to explain it as well - the graph at the bottom of that link is really useful. Is there a separate hydrology docs PR planned?

**Review by jacobcook1995 — APPROVED** [review]
LGTM!

**Comment by vgro** [comment]
> LGTM - this makes a lot of sense and that LISFLOOD solution looks very pragmatic. It would be good to add citations and maybe a slightly fuller explanatation of the shape parameter. I didn't really get it until I went to look at https://ec-jrc.github.io/lisflood-model/2_09_stdLISFLOOD_preferential-bypass
> 
> This does need docs to explain it as well - the graph at the bottom of that link is really useful. Is there a separate hydrology docs PR planned?

There is no separate documentation for the hydrology model, I was hoping that the docstrings will cover the most important point and refer to more detailed sources, like LISFLOOD. I'm happy to expand further here (most functions probably need a bit more detailed descriptions as they get established).

**Comment by davidorme** [comment]
I think we'll need a user-facing doc page for the hydrology model at some point. That should probably explain the features and parameterisation, but that may be for a later date.

**Comment by vgro** [comment]
> I think we'll need a user-facing doc page for the hydrology model at some point. That should probably explain the features and parameterisation, but that may be for a later date.

I agree. I will put this on my list and do in a separate PR once all the main features are implemented.

**Pull request merged**
