### PR TITLE
Update API docstrings and automodule structure

### LINKED ISSUE #142: Table of content issue for API
What we are currently doing to document the API is to put all of the content as docstrings in module files. So, for example, we could have the following - the only trick here is that to get a top-level RST header in the docstring (using the `*` line), we need to suppress `flake8` complaining about the missing blank line.

```python
"""API for module.py.
******************

RST content for the module.
""" # noqa: D205

def member() -> None:
    """A function module.member."""
    pass
```

The idea then is that in the sphinx documents (written using Myst markdown), we can create a stub file for the API for `module.py` and just have `docs/source/api/module.md` as:

````markdown
---
jupytext:
  cell_metadata_filter: -all
  formats: md:myst
  main_language: python
  text_representation:
    extension: .md
    format_name: myst
    format_version: 0.13
    jupytext_version: 1.13.8
kernelspec:
  display_name: vr_python3
  language: python
  name: vr_python3
---

```{eval-rst}
.. automodule:: virtual_rainforest.core.readers
 :autosummary:
 :members:
 :special-members: __init__
```
````

 And that works - the page is rendered with the title from the module docstring as the top header and all is well _on the page_. See for example the test build [here](https://virtual-rainforest.readthedocs.io/en/feature-data_system/api/core/data.html)

The problem is that then referencing that markdown file in a `toctree` directive for some reason drags all of the module members into the ToC content - not nested in a dropdown, just in a long list. Not all _headings_ within the content for some reason, just the top header and members. You can see the result in the ToC on  the link above.

If I include a single top level header in the source `md` file (betwee
ends up including all of the section headings and code objects from the file. This is why the API Reference menu on this build looks so shambolic: https://virtual-rainforest.readthedocs.io/en/feature-data_system/api/core.html
 
If I include a top level header in the markdown file as below, then all of that goes away and we just get that top level header in the ToC (but of course an extra top level header in the content). My instinct is that this is something to do with `max-depth` but the code members in the ToC aren't in the HTML as headers with a depth. Not a clue why this is happening.
 

````markdown
---
jupytext:
  cell_metadata_filter: -all
  formats: md:myst
  main_language: python
  text_representation:
    extension: .md
    format_name: myst
    format_version: 0.13
    jupytext_version: 1.13.8
kernelspec:
  display_name: vr_python3
  language: python
  name: vr_python3
---

# Module API

```{eval-rst}
.. automodule:: virtual_rainforest.core.readers
 :autosummary:
 :members:
 :special-members: __init__
```
````

### PR DESCRIPTION
**Pull request by davidorme**
# Description

This PR is off the back of #157 , which documented the documentation approach for the package. The commits here update the existing module docstrings, API stubs in the `source/api` folder and the `index.md`. It:

* Imposes the standard style described in #157 across the code and docs
* Removes the widespread inclusion of `__init__` in documentation, and we aren't using `__init__` docstrings.
* Fixes #142 by systematically removing the structures that creates the issue.

Things it does not do:

* It does _not_ solve the odd issue with the foldable page submenus not appearing from the TOC. 
* Address the general problem of the overcomplex sidebar - we probably want section by section `index.md` files to control the level of detail in any one section of the TOC.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [x] Bug fix (non-breaking change which fixes an issue)

## Key checklist

- [ ] Make sure you've run the `pre-commit` checks: `$ pre-commit run -a`
- [ ] All tests pass: `$ poetry run pytest`

## Further checks

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by davidorme** [comment]
I probably should have waited until #159 is merged first. Either way, this is now ready to be updated to that merge and then pulled in.

**Review by jacobcook1995 — APPROVED** [review]
LGTM!

**Comment by jacobcook1995** [comment]
Was wondering what "It does not solve the odd issue with the foldable page submenus not appearing from the TOC." means, is that sometimes content we add to the TOC doesn't end up in the sidebar?

**Comment by davidorme** [comment]
The content does appear, but it should also generate a folding submenu (little plus in a circle to the left) to show the headings within the document...

**Review by alexdewar — APPROVED** [review]
LGTM

**Review by dalonsoa — APPROVED** [review]
Also looks good tome. Documentation syntax is so obscure, sometimes...

**Pull request merged**
