### PR TITLE
Add flake8-docstrings

### LINKED ISSUE #36: Check docstrings as part of pre-commit, CI etc.
This is just a suggestion, but I've done it for our own projects and found it useful.

There are various tools you can use to do this, but I've been using
``flake8-docstring``.

You can configure it to e.g. mandate docstrings for public functions, which would help
catch problems like #30.

Just a suggestion!

### PR DESCRIPTION
**Pull request by dalonsoa**
# Description

Adds `flake8-docstrings` plugin to check the docstrings in the code while running the linter. 

Fixes #36 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Key checklist

- [x] Make sure you've run the `pre-commit` checks: `$ pre-commit run -a`
- [x] All tests pass: `$ poetry run pytest`

## Further checks

N/A

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by LivDaniel** [comment]
I'm not sure I have enough knowledge to be a competent reviewer on this. My only thought was did David say we should exclude Fiona for now or did we decide to keep it in?

**Review by LivDaniel — APPROVED** [review]

**Comment by davidorme** [comment]
I think we should also add this to `pre-commit` as well:

```
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]
```

**Comment by dalonsoa** [comment]
Done!

**Comment by davidorme** [comment]
Ack. Should have expected that the docstrings would fail. I did some fixing in the PR for #51 - not sure if I hit all of them.

**Comment by dalonsoa** [comment]
I'll try to sort this out on Monday

**Comment by davidorme** [comment]
It's failing on *my* messy docstrings 😞  I've merged in from develop and cleaned up the remaining ones.

**Review by davidorme — APPROVED** [review]

**Pull request merged**
