### PR TITLE
old abiotic model deleted, docs updated

### PR DESCRIPTION
**Pull request by vgro**
This PR deletes the process-based version of the `abiotic` model from develop. The model was not up-to-date with the model structure and a lot of it needs to be rewritten to work well with other models, so we felt that it would be best to move it to a different branch and tag it for later reference.

In the course of this, I updated the model description.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Key checklist

- [x] Make sure you've run the `pre-commit` checks: `$ pre-commit run -a`
- [x] All tests pass: `$ poetry run pytest`

## Further checks

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Review by jacobcook1995 — APPROVED** [review]
LGTM.

Have you decided how you are going to tag the repo so you can find the point before all this got deleted? Personally reckon that the best way forward is adding a tag to `develop` **before** this pull request gets merged, so that then the tag will point you to the state of `develop` just before deletion (see [here](https://git-scm.com/book/en/v2/Git-Basics-Tagging)). That feels safer longer term than a separate branch which you'll have to remember not to delete

**Comment by jacobcook1995** [comment]
I'm not sure if you can add a tag to develop directly, you might have to make another PR that changes nothing from develop aside adding a tag, and then merge that PR in

**Comment by vgro** [comment]
> LGTM.
> 
> Have you decided how you are going to tag the repo so you can find the point before all this got deleted? Personally reckon that the best way forward is adding a tag to `develop` **before** this pull request gets merged, so that then the tag will point you to the state of `develop` just before deletion (see [here](https://git-scm.com/book/en/v2/Git-Basics-Tagging)). That feels safer longer term than a separate branch which you'll have to remember not to delete

I added a tag to the branch where I parked it, I couldn't find out how to link this to this conversation, but if you go to the start page of the VR there is a tag next to the branches at the top.

**Comment by vgro** [comment]
> I'm not sure if you can add a tag to develop directly, you might have to make another PR that changes nothing from develop aside adding a tag, and then merge that PR in

I think that's basically what I did
https://github.com/ImperialCollegeLondon/virtual_rainforest/releases/tag/old_abiotic_model

**Comment by vgro** [comment]
> > LGTM.
> > Have you decided how you are going to tag the repo so you can find the point before all this got deleted? Personally reckon that the best way forward is adding a tag to `develop` **before** this pull request gets merged, so that then the tag will point you to the state of `develop` just before deletion (see [here](https://git-scm.com/book/en/v2/Git-Basics-Tagging)). That feels safer longer term than a separate branch which you'll have to remember not to delete
> 
> I added a tag to the branch where I parked it, I couldn't find out how to link this to this conversation, but if you go to the start page of the VR there is a tag next to the branches at the top.

https://github.com/ImperialCollegeLondon/virtual_rainforest/releases/tag/old_abiotic_model

**Comment by jacobcook1995** [comment]
Ahh right, yes I can see that on the main repo! Yeah think it's good to go then!

(I think my confusion arose as I didn't realise you could add a tag to a protected branch directly, but actually it's essentially not much different from making a branch so why wouldn't you be allowed)

**Comment by davidorme** [comment]
@jacobcook1995 Yeah - tagging the commit in `develop` and tagging a new branch are pretty similar. Using a branch gives you something you can work on if you want to try and update the code before bringing it back into `develop`.  It seems marginally easier to use a branch to switch back and forth: `git switch dead_model_branch` as opposed to `git switch --detach dead_model_tag`

https://stackoverflow.com/questions/4330610/switch-to-another-git-tag

**Review by davidorme — APPROVED** [review]
LGTM

**Pull request merged**
