### PR TITLE
Update ci.yml to use CODECOV_TOKEN

### PR DESCRIPTION
**Pull request by dalonsoa**
# Description

It seems you need a token now to upload coverage reports to Codecov, so here it is. 

Fixes # (issue)

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [x] Bug fix (non-breaking change which fixes an issue)

## Key checklist
N/A
- [ ] Make sure you've run the `pre-commit` checks: `$ pre-commit run -a`
- [ ] All tests pass: `$ poetry run pytest`

## Further checks
N/A
- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by davidorme** [comment]
Does that differ from this commit to #384 : https://github.com/ImperialCollegeLondon/virtual_rainforest/pull/384/commits/1ad61b031392a6bcae827b21497b56976db01264

Also, it looks like the `codecov` upload doesn't complete, even though the action doesn't fail:
https://github.com/ImperialCollegeLondon/virtual_rainforest/actions/runs/7801415615/job/21276472911?pr=385#step:7:60

Where is that `secrets.CODECOV_TOKEN` value actually set?

**Comment by davidorme** [comment]
> Anyway, yes, the main difference is that I've added the secret to the repo. I'm not sure why you need me, though. Any repo admin should be able to do it.

Honestly, it wasn't clear how to generate the token and whether that is per repo or per user - in which case it would be an `ImperialCollegeLondon` wide token?

**Comment by dalonsoa** [comment]
@davidorme , sorted! It seems it did not like using environment variables, but the token needed to be provided directly. I've also added a couple more flags to the coverage upload. 

Feel free to ignore this PR and implement these changes in #384 directly

**Comment by davidorme** [comment]
Fantastic! Just for the record,  how did you generate the token to put in the secrets settings?

**Comment by dalonsoa** [comment]
In the settings tab in Codecov. Maybe that's where I'm needed... 

Screenshot from 2024-02-07 08-13-42

**Comment by davidorme** [comment]
Exactly where you're needed, I think 😄 I have a feeling that secrets can be set at the Org level, so that this wouldn't have to be enabled on a per repo basis.

**Comment by davidorme** [comment]
Handled along with other changes over in #384

**Pull request closed without merging**
