### PR TITLE
Update typing of `config` arguments.

### LINKED ISSUE #294: Incorrect typing in `BaseModel.from_config` args
**Describe the bug**
The `config` argument to `core.base_model.BaseModel.from_config` is typed as a dict:

https://github.com/ImperialCollegeLondon/virtual_rainforest/blob/173c79130acfad2dd93ec83e8a6d690cdfcf6018/virtual_rainforest/core/base_model.py#L219-L224

With the updated `Config` object, we should probably type this as a `Config` instead.

**Expected behavior**

I think this just needs an import in `core.base_model.BaseModel.from_config` and then changing the types in the BaseModel and subclass methods.

@jacobcook1995 Does that sound right?

### PR DESCRIPTION
**Pull request by davidorme**
# Description

This PR:
* Updates the BaseModel to type the `config` argument as the `Config` object, not just a generic `dict[str, Any]`
* Updates all of the models to also use that typing
* Updates other uses of `config` args in `core`.
* In particular `data.load_from_config` gets an overhaul: it now takes a `Config` object rather than a section from the dict  (`cfg['core']['data']`) and does some more validation of the contents, including logging a warning if the data section is there (which it is by default) but does not define any sources.
* Updates tests, docstrings and the user docs for creating new model classes.

Edited to add:

* This PR also suggested that having a direct method to create `Config` objects, without having to keep files or write Mockers to fake `Paths` or content would simplify a lot of testing. I've added a `cfg_string` argument to `Config.__init__` that provides an alternate source of the configuration TOML data. `vr_run` now also accepts this argument. 
* Updated tests of `Config` to check it works.
* Updated tests of `data` to use simpler string and remove redundant files
* Updated tests of main to allow a full config process rather than Mocking it.

Fixes #294 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [x] Bug fix (non-breaking change which fixes an issue)

## Key checklist

- [x] Make sure you've run the `pre-commit` checks: `$ pre-commit run -a`
- [x] All tests pass: `$ poetry run pytest`

## Further checks

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by davidorme** [comment]
@jacobcook1995 The current failure is due to one of the `vr_run` tests. The mocker was injecting a model `topsoil` and failing it with an initialisation error. With the test now using the full config process, this fails much earlier, because there is no `topsoil` model schema, so the config can't even be validated. I think this test is redundant?

**Comment by jacobcook1995** [comment]
I think that test (and the behaviour it is testing) is redundant if generating a `Config` object now leads to an error if a schema can't be found. I don't think there's any need to add another check for model `__init__` failures as there's a few already and this test was designed to specifically test the step to catch missing models.

**Review by jacobcook1995 — APPROVED** [review]
The changes all look good to me. I'm not sure why the `vr_run` test is failing, but that definitely needs fixing

**Comment by davidorme** [comment]
> The broken test could be replaced by a test that takes in a valid config as a string, and then mocks the `MODEL_REGISTRY` to not include one of the models provided in `[core.modules]`. This would then catch the test that models that have schemas but have not been registered properly in the `MODEL_REGISTRY` are handled correctly in the main loop.

But that is then a test of a model registry issue, not of failing to initialise a properly registered model due to configuration with data that meets the schema but not the fine details. I'll add a second test of the another config issue, just for variety,

**Comment by jacobcook1995** [comment]
Yeah it is though the test is a test of the `vr_run` function not a configuration specific function, so having tests that test `vr_run`'s handling of various errors is probably sensible right?

**Comment by davidorme** [comment]
> However, that might be an overly complex test to add given that `select_models` (which raises the relevant exception) is already tested, and that we are planning to combine the model, schema, and constants registries (see #302 )

Yeah - I think forcing a test of behaviour that would only happen if `select_models` breaks is too complex - as you say I think this whole API is likely to change shortly.

**Pull request merged**
